# SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
# SET GLOBAL SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';
SET GLOBAL SQL_MODE = '';
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";