
spring:
  application:
    name: springboot-ecommerce-course1-db
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/onion-db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: onion-user
    password: onion1!
    # HikariCP 설정
    hikari:
      # pool 이름 지증
      pool-name: HikariCP
      # 최대 Pool 크기 지정
      maximum-pool-size: 10
      # 최소 유휴 연결 수 지정
      minimum-idle: 5
      # 유휴 연결이 닫히기 전까지의 시간(ms) (너무 짧으면 커넥션이 비정상 종료될 수 있음)
      idle-timeout: 60000
      # 연결을 얻기 위해 기다리는 최대 시간(ms)
      connection-timeout: 30000 # 30초
      # 연결의 최대 수명(ms)
      max-lifetime: 1800000 # 30분 (기본값 유지)
      # 연결 테스트에 사용할 쿼리
      connection-test-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    # JPA SQL을 로그에 보여줌
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  devtools:
    restart:
      enabled: false

springdoc:
  open-api:
    version: 0.0.1
    info:
      title: 대용량 트래픽 처리를 위한 데이터베이스 첫 걸음
      description: 100만 유저를 견디는 서버 구축 가이드
      version: 0.0.1
      contact:
        name: db
        email: db@freelife.com
        url: https://github.com/freelife1191/springboot-ecommerce-course1-db
  api-docs:
    enabled: true
  swagger-ui:
    path: /docs
    deep-linking: true
    disable-swagger-default-url: true
    enabled: true
    persist-authorization: false
    operations-sorter: method
    tags-sorter: alpha
    show-common-extensions: true
    syntax-highlight:
      theme: obsidian
      activated: true
    show-extensions: true
    doc-expansion: list
    groups-order: asc
  model-and-view-allowed: true
  show-actuator: false
  enable-spring-security: true

logging:
  level:
    root: info
    org.springframework.web: INFO
    com.onion: debug
    org.springdoc: debug
    # com.zaxxer.hikari: DEBUG