services: # 이 항목 밑에 실행하려는 컨테이너 들을 정의 ( 컴포즈에서 컨테이너 : 서비스 )
  mysql-master-a: # 서비스 명
    # amd64 아키텍처로 실행
    platform: linux/amd64
    # 기본 MySQL 이미지 사용
    image: mysql:5.7
    restart: always
    ports:
      - "13306:3306" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)  <- 컨테이너 내부는 무조건 3306
    environment: # -e 옵션
      MYSQL_ROOT_PASSWORD: onion1!
      MYSQL_DATABASE: onion-db
      MYSQL_USER: onion-user
      MYSQL_PASSWORD: onion1!
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
      TZ: Asia/Seoul
    volumes:
      - db_data_master_a:/var/lib/mysql
    command: # 명령어 실행
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-time-zone=+9:00
      - --max_connections=1000
    networks:
      - mysql-network

volumes:
  db_data_master_a:

networks:
  mysql-network:
    driver: bridge